function A = DHCraig(alpha, a, d, tetha)
    A = [cos(tetha)                   -sin(tetha)                    0                  a;...
         sin(tetha)*(cos(alpha))  cos(tetha)*(cos(alpha)) -(sin(alpha)) -d*(sin(alpha));...
         sin(tetha)*(sin(alpha))  cos(tetha)*(sin(alpha))  (cos(alpha))  d*(cos(alpha));...
         0                             0                             0                  1                 ];
end