function [B] = rotacionX(A, theta)
    rotX = [1 0            0           0;...
            0 cosd(theta) -sind(theta) 0;...
            0 sind(theta)  cosd(theta) 0;...
            0 0            0           1];
    B = A*rotX;
end