function [B] = rotacionY(A, theta)
    rotY = [ cosd(theta) 0 sind(theta) 0;...
             0           1 0           0;...
            -sind(theta) 0 cosd(theta) 0;...
             0           0 0           1];
    B = A*rotY;
end